name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Ari-147
      
          outputs: |
            dist/github-snake.svg
    
          color_snake: "#22d3ee"
          color_dots: "#0ea5e9,#2563eb,#1d4ed8,#020617"
          color_background: "#020617"
          color_empty: "#0f172a"
#fixed
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
